# Generated by Django 4.1.3 on 2023-10-07 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=100)),
                ("class_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                ("trainer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("speciality", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "subscription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("subscription_date", models.DateField()),
                (
                    "class_field",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitnessClub.class",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitnessClub.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("membership_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitnessClub.client",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fitnessClub.trainer"
            ),
        ),
    ]
