name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 .
  tests:
    name: Тесты
    
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          ENGINE: 'django.db.backends.postgresql'
          NAME: 'github_actions'
          USER: postgres
          PASSWORD: postgres
          HOST: '127.0.0.1'
          PORT: '54320'
        ports:
          - 54320:54320
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest-django
      - uses: harmon758/postgresql-action@v1
        with:
           postgresql version: '14.1'
      - name: Wait for PostgreSQL to start
        run: sleep 10
      - name: Run migrations
        run: python project/manage.py migrate
      - name: Run tests
        run: python project/manage.py test
