name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 .
  tests:
    name: Тесты
    
    runs-on: ubuntu-latest
    
    services:
      postgresql:
        image: postgres
        env:         
          POSTGRES_DB: 'postgres'
          DB_CONNECTION: 'pgsql'
          DB_HOST: 'postgresql'
          DB_PORT: '5432'
          DB_DATABASE: 'postgres'
          DB_USERNAME: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
        ports:
          - 54320:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest-django
      - uses: harmon758/postgresql-action@v1
        with:
           postgresql version: '14.1'
      - name: Wait for PostgreSQL to start
        run: sleep 10
      - name: Run migrations
        run: python3 project/manage.py migrate
      - name: Run tests (models)
        run: python3 project/manage.py test tests.test_models
      - name: Run tests (class)
        run: python3 project/manage.py test tests.test_rest_class
      - name: Run tests (client)
        run: python3 project/manage.py test tests.test_rest_client
      - name: Run tests (IndividualTraining)
        run: python3 project/manage.py test tests.test_rest_IndividualTraining
      - name: Run tests (membership)
        run: python3 project/manage.py test tests.test_rest_membership
      - name: Run tests (subscription)
        run: python3 project/manage.py test tests.test_rest_subscription
      - name: Run tests (trainer)
        run: python3 project/manage.py test tests.test_rest_trainer
      - name: Run tests (views)
        run: python3 project/manage.py test tests.test_views
